---
title: "R Notebook"
output: html_notebook
---

*Libraries*

```{r}
pkgs <- c('tidyverse', 'MultiAssayExperiment', 'data.table',"DESeq2","plotly")
suppressPackageStartupMessages(sapply(pkgs, require, character.only = T))
```

*Functions*

```{r}
classifyDEGs <- function(de_result, # DE Result Table (data.frame)
                         pThrs = 0.01, fcThrs = 0) # Thresholds
  {
  with(de_result, ifelse(pvalue < pThrs & log2FoldChange < -fcThrs, "Down",
                       ifelse(pvalue < pThrs & log2FoldChange > fcThrs, "Up","Unchanged")))
}
plotVolcano <- function(de_result) {
  temp = de_result %>% mutate(logp = -log10(pvalue), score = logp*abs(log2FoldChange))
  pal <- setNames(c("darkred", "grey", "dodgerblue"), c("Up", "Unchanged", 'Down'))
  plt = plot_ly(data = temp, x = ~log2FoldChange, y = ~logp,
                color = ~DEG, colors = pal, 
                text = rownames(de_result), size = ~score)
  plt
}
```

**AGES**

```{r}
file_path = "~/Documents/work/SpnCarriage_Analysis/data/raw_data/AGES/Robj/AGES_studyObj.rds"
ages = readRDS(file_path)
rnaseq = ages[["RNA-Seq"]]
rnaseq_subset = rnaseq[,which(rnaseq$timepoint == "baseline" & rnaseq$sex == "F")]
rnaseq_subset
```

```{r}
dds = DESeqDataSet(rnaseq_subset, design = ~ carriage)
dds = DESeq(dds)
de_result = results(dds) %>% as.data.frame %>% filter(complete.cases(log2FoldChange))
de_result
```

```{r}
de_result$DEG <- classifyDEGs(de_result)
plotVolcano(de_result)
```

**MUCOSAL**

```{r}
count_fpath = "~/Documents/work/SpnCarriage_Analysis/data/raw_data/MUCOSAL/rnaseq/PILOT_rnaseq_data.tsv"
meta_fpath = "~/Documents/work/SpnCarriage_Analysis/data/raw_data/MUCOSAL/rnaseq/PILOT_rnaseq_meta.tsv"
```

**LAIV1**

```{r}

```

**LAIV2**
